### ISSUE TITLE
Error in  _update_densest_tick()

### ISSUE THREAD

**Issue by cdrose** [kivy-garden/garden.tickline#1]
I'm not sure if this is a python 3 compatibility thing, but on line 815 in **init**.py

  i = bisect(tol, scale)

needs to be

  i = bisect(tol, (scale,))

to avoid a TypeError: unorderable types: float() < tuple()

**Comment by eulerreich** [comment]
Try replacing that line with

``` python
i = bisect([t[0] for t in tol], scale)
```

Let me know if it works.

**Comment by cdrose** [comment]
Yup that works also.

**Comment by eulerreich** [comment]
I forgot to close this issue in the commit message, but I'll just add a note here manually.

Commit 1c1366989fe205a047ad352ddb469936edd92171 fixed this issue.
